import type convert from 'color-convert';

export type ColorLike = Color | string | ArrayLike<number> | number | Record<string, any>;
export type ColorJson = {model: string; color: number[]; valpha: number};
export type ColorObject = {alpha?: number | undefined} & Record<string, number>;
export type ColorInstance = Color;

type Color = {
	toString(): string;
	// eslint-disable-next-line @typescript-eslint/naming-convention
	toJSON(): ColorJson;
	string(places?: number): string;
	percentString(places?: number): string;
	array(): number[];
	object(): ColorObject;
	unitArray(): number[];
	unitObject(): {r: number; g: number; b: number; alpha?: number | undefined};
	round(places?: number): Color;
	alpha(): number;
	alpha(value: number): Color;
	red(): number;
	red(value: number): Color;
	green(): number;
	green(value: number): Color;
	blue(): number;
	blue(value: number): Color;
	hue(): number;
	hue(value: number): Color;
	saturationl(): number;
	saturationl(value: number): Color;
	lightness(): number;
	lightness(value: number): Color;
	saturationv(): number;
	saturationv(value: number): Color;
	value(): number;
	value(value: number): Color;
	chroma(): number;
	chroma(value: number): Color;
	gray(): number;
	gray(value: number): Color;
	white(): number;
	white(value: number): Color;
	wblack(): number;
	wblack(value: number): Color;
	cyan(): number;
	cyan(value: number): Color;
	magenta(): number;
	magenta(value: number): Color;
	yellow(): number;
	yellow(value: number): Color;
	black(): number;
	black(value: number): Color;
	x(): number;
	x(value: number): Color;
	y(): number;
	y(value: number): Color;
	z(): number;
	z(value: number): Color;
	l(): number;
	l(value: number): Color;
	a(): number;
	a(value: number): Color;
	b(): number;
	b(value: number): Color;
	keyword(): string;
	keyword<V extends string>(value: V): Color;
	hex(): string;
	hex<V extends string>(value: V): Color;
	hexa(): string;
	hexa<V extends string>(value: V): Color;
	rgbNumber(): number;
	luminosity(): number;
	contrast(color2: Color): number;
	level(color2: Color): 'AAA' | 'AA' | '';
	isDark(): boolean;
	isLight(): boolean;
	negate(): Color;
	lighten(ratio: number): Color;
	darken(ratio: number): Color;
	saturate(ratio: number): Color;
	desaturate(ratio: number): Color;
	whiten(ratio: number): Color;
	blacken(ratio: number): Color;
	grayscale(): Color;
	fade(ratio: number): Color;
	opaquer(ratio: number): Color;
	rotate(degrees: number): Color;
	mix(mixinColor: Color, weight?: number): Color;
	rgb(...arguments_: number[]): Color;
	hsl(...arguments_: number[]): Color;
	hsv(...arguments_: number[]): Color;
	hwb(...arguments_: number[]): Color;
	cmyk(...arguments_: number[]): Color;
	xyz(...arguments_: number[]): Color;
	lab(...arguments_: number[]): Color;
	lch(...arguments_: number[]): Color;
	ansi16(...arguments_: number[]): Color;
	ansi256(...arguments_: number[]): Color;
	hcg(...arguments_: number[]): Color;
	apple(...arguments_: number[]): Color;
};

export type ColorConstructor = {
	(object?: ColorLike, model?: keyof (typeof convert)): Color;
	new(object?: ColorLike, model?: keyof (typeof convert)): Color;
	rgb(...value: number[]): Color;
	rgb(color: ColorLike): Color;
	hsl(...value: number[]): Color;
	hsl(color: ColorLike): Color;
	hsv(...value: number[]): Color;
	hsv(color: ColorLike): Color;
	hwb(...value: number[]): Color;
	hwb(color: ColorLike): Color;
	cmyk(...value: number[]): Color;
	cmyk(color: ColorLike): Color;
	xyz(...value: number[]): Color;
	xyz(color: ColorLike): Color;
	lab(...value: number[]): Color;
	lab(color: ColorLike): Color;
	lch(...value: number[]): Color;
	lch(color: ColorLike): Color;
	ansi16(...value: number[]): Color;
	ansi16(color: ColorLike): Color;
	ansi256(...value: number[]): Color;
	ansi256(color: ColorLike): Color;
	hcg(...value: number[]): Color;
	hcg(color: ColorLike): Color;
	apple(...value: number[]): Color;
	apple(color: ColorLike): Color;
};

// eslint-disable-next-line @typescript-eslint/no-redeclare, @typescript-eslint/naming-convention
declare const Color: ColorConstructor;

export default Color;
